/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.example;

import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {

    @BeforeAll
    static void load() {
        App.loadLibrary();
    }

    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.greetingTo("Cris"), "Hello, Cris");
    }

    @Test
    void emptyWillBeThrown() {
        App app = new App();
        assertThrows(IllegalArgumentException.class, () -> app.greetingTo(""));
    }
}
